/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Admin
 */
public class splash extends javax.swing.JFrame {

    /**
     * Creates new form splash
     */
    public splash() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTime = new javax.swing.JLabel();
        lbGif = new javax.swing.JLabel();
        pbrTime = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        lbBackround = new javax.swing.JLabel();

        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTime.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lbTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTime.setText("Loading...");
        jPanel1.add(lbTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 110, -1));

        lbGif.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/run_32px.gif"))); // NOI18N
        jPanel1.add(lbGif, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, -100, 40, 30));
        jPanel1.add(pbrTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 230, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("QUIZGAME - REALTIME");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        lbBackround.setBackground(new java.awt.Color(255, 255, 255));
        lbBackround.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBackround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Have some question_.gif"))); // NOI18N
        lbBackround.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lbBackroundMouseDragged(evt);
            }
        });
        lbBackround.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbBackroundMousePressed(evt);
            }
        });
        jPanel1.add(lbBackround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 400, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(392, 296));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    int mouseX, mouseY;
    private void lbBackroundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBackroundMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_lbBackroundMousePressed

    private void lbBackroundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBackroundMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        // Di chuyển frame theo chuột
        this.setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_lbBackroundMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new splash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbBackround;
    public static javax.swing.JLabel lbGif;
    public static javax.swing.JLabel lbTime;
    public static javax.swing.JProgressBar pbrTime;
    // End of variables declaration//GEN-END:variables
}
